import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#0c0c0e' },
  header: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  eyebrow: { color: '#7f9660', fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  title: { color: '#f0f0f0', fontSize: 24, fontWeight: '700', marginTop: 4 },
  addButton: { backgroundColor: '#dce9bd', borderRadius: 7, paddingHorizontal: 15, paddingVertical: 11 },
  addButtonText: { color: '#17200c', fontSize: 13, fontWeight: '800' },
  toolbar: { paddingHorizontal: 16, paddingVertical: 12, flexDirection: 'row', alignItems: 'center', gap: 12 },
  search: { flex: 1, height: 42, borderWidth: 1, borderColor: '#303036', backgroundColor: '#151518', color: '#ededed', borderRadius: 7, paddingHorizontal: 13, fontSize: 14 },
  count: { color: '#85858c', fontSize: 12, minWidth: 32, textAlign: 'right' },
  list: { paddingHorizontal: 16, paddingBottom: 40 },
  row: { minHeight: 92, borderBottomWidth: 1, borderBottomColor: '#26262b', paddingVertical: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  rowInfo: { flex: 1, minWidth: 0 },
  manufacturer: { color: '#75757d', fontSize: 10, fontWeight: '700', textTransform: 'uppercase' },
  name: { color: '#e5e5e5', fontSize: 15, lineHeight: 20, fontWeight: '600', marginTop: 3 },
  price: { color: '#9ea582', fontSize: 13, fontWeight: '700', marginTop: 6 },
  actions: { flexDirection: 'row', gap: 6 },
  editButton: { borderWidth: 1, borderColor: '#3a3a41', borderRadius: 6, paddingHorizontal: 11, paddingVertical: 8 },
  editText: { color: '#c7c7cc', fontSize: 12, fontWeight: '700' },
  deleteButton: { borderWidth: 1, borderColor: '#57343a', borderRadius: 6, paddingHorizontal: 11, paddingVertical: 8 },
  deleteText: { color: '#d58b94', fontSize: 12, fontWeight: '700' },
  center: { flex: 1, minHeight: 220, alignItems: 'center', justifyContent: 'center', padding: 30 },
  emptyTitle: { color: '#d0d0d4', fontSize: 16, fontWeight: '700' },
  emptyBody: { color: '#66666d', fontSize: 13, marginTop: 7 },
  errorBanner: { marginHorizontal: 16, marginBottom: 6, backgroundColor: '#2b1b1f', borderWidth: 1, borderColor: '#59343c', borderRadius: 7, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 12 },
  errorText: { flex: 1, color: '#e3a0a8', fontSize: 12 },
  dismiss: { color: '#e3a0a8', fontSize: 12, fontWeight: '800' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  modalPanel: { width: '100%', maxWidth: 720, maxHeight: '92%', backgroundColor: '#151518', borderWidth: 1, borderColor: '#35353b', borderRadius: 8, overflow: 'hidden' },
  modalHeader: { padding: 20, borderBottomWidth: 1, borderBottomColor: '#2c2c31', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  modalEyebrow: { color: '#8fa36c', fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
  modalTitle: { color: '#eeeeef', fontSize: 20, fontWeight: '700', marginTop: 4 },
  closeButton: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  closeText: { color: '#a0a0a7', fontSize: 27, lineHeight: 28 },
  form: { padding: 20, flexDirection: 'row', flexWrap: 'wrap', columnGap: 14, paddingBottom: 10 },
  field: { width: '48%', minWidth: 220, flexGrow: 1, marginBottom: 15 },
  label: { color: '#a7a7ad', fontSize: 11, fontWeight: '700', marginBottom: 7 },
  input: { height: 43, borderWidth: 1, borderColor: '#37373d', backgroundColor: '#0e0e10', color: '#ededed', borderRadius: 6, paddingHorizontal: 12, fontSize: 14 },
  multiline: { height: 86, paddingTop: 11, textAlignVertical: 'top' },
  switchRow: { height: 43, borderWidth: 1, borderColor: '#37373d', backgroundColor: '#0e0e10', borderRadius: 6, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  switchValue: { color: '#b8b8bd', fontSize: 13 },
  formError: { width: '100%', color: '#e79ba4', fontSize: 12, marginBottom: 10 },
  formActions: { borderTopWidth: 1, borderTopColor: '#2c2c31', padding: 14, flexDirection: 'row', justifyContent: 'flex-end', gap: 8 },
  cancelButton: { borderWidth: 1, borderColor: '#3b3b41', borderRadius: 6, paddingHorizontal: 19, paddingVertical: 11 },
  cancelText: { color: '#b7b7bc', fontWeight: '700' },
  saveButton: { backgroundColor: '#dce9bd', borderRadius: 6, paddingHorizontal: 24, paddingVertical: 11, minWidth: 82, alignItems: 'center' },
  saveText: { color: '#17200c', fontWeight: '800' },
  disabled: { opacity: 0.5 },
});
