import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';

export const styles = StyleSheet.create({
  header: { marginTop: 16, marginBottom: 24 },
  eyebrow: { color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.5 },
  title: { color: colors.text, fontSize: 24, fontWeight: '700', marginTop: 5 },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 8, padding: 24, alignItems: 'center' },
  avatarButton: { width: 86, height: 86, marginBottom: 14 },
  avatar: { width: 82, height: 82, borderRadius: 41 },
  avatarFallback: { width: 82, height: 82, borderRadius: 41, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  cameraBadge: { position: 'absolute', right: 0, bottom: 0, width: 27, height: 27, borderRadius: 14, backgroundColor: colors.primary, borderWidth: 3, borderColor: colors.surface, alignItems: 'center', justifyContent: 'center' },
  cameraMark: { color: colors.primaryInk, fontSize: 18, fontWeight: '800', lineHeight: 19 },
  uploadOverlay: { position: 'absolute', top: 0, left: 0, width: 82, height: 82, borderRadius: 41, backgroundColor: 'rgba(0,0,0,0.62)', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: colors.primaryInk, fontSize: 27, fontWeight: '700' },
  nickname: { color: colors.text, fontSize: 20, fontWeight: '700' },
  email: { color: colors.textMuted, fontSize: 12, marginTop: 6 },
  editProfileButton: { marginTop: 18, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: 7, paddingHorizontal: 18, paddingVertical: 10 },
  editProfileText: { color: colors.textSecondary, fontSize: 12, fontWeight: '700' },
  profileError: { color: colors.danger, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 12 },
  logoutButton: { marginTop: 18, borderWidth: 1, borderColor: colors.border, borderRadius: 7, paddingVertical: 13, alignItems: 'center' },
  logoutText: { color: colors.textMuted, fontWeight: '600' },
  withdrawButton: { marginTop: 8, paddingVertical: 11, alignItems: 'center' },
  withdrawText: { color: '#b86f78', fontSize: 12, fontWeight: '600' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.72)', alignItems: 'center', justifyContent: 'center', padding: 18 },
  modalPanel: { width: '100%', maxWidth: 440, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderStrong, borderRadius: 8, padding: 22 },
  modalEyebrow: { color: colors.primary, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 },
  modalTitle: { color: colors.text, fontSize: 21, fontWeight: '700', marginTop: 4, marginBottom: 20 },
  fieldLabel: { color: '#9b9ba1', fontSize: 11, fontWeight: '700', marginBottom: 7, marginTop: 12 },
  readonlyInput: { height: 43, borderWidth: 1, borderColor: '#2d2d32', backgroundColor: '#111114', borderRadius: 6, paddingHorizontal: 12, justifyContent: 'center' },
  readonlyText: { color: '#66666d', fontSize: 14 },
  input: { height: 43, borderWidth: 1, borderColor: '#45454c', backgroundColor: '#0f0f11', color: '#ededed', borderRadius: 6, paddingHorizontal: 12, fontSize: 14 },
  helperText: { color: '#65656c', fontSize: 11, lineHeight: 16, marginTop: 7 },
  errorText: { color: '#df929b', fontSize: 12, marginTop: 12 },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 8, marginTop: 22 },
  cancelButton: { borderWidth: 1, borderColor: '#3b3b41', borderRadius: 6, paddingHorizontal: 18, paddingVertical: 11 },
  cancelText: { color: '#b7b7bc', fontWeight: '700' },
  saveButton: { backgroundColor: colors.primary, borderRadius: 6, paddingHorizontal: 22, paddingVertical: 11, minWidth: 78, alignItems: 'center' },
  saveText: { color: colors.primaryInk, fontWeight: '800' },
  disabled: { opacity: 0.5 },
  dangerButton: { backgroundColor: '#b94f5b', borderRadius: 6, paddingHorizontal: 18, paddingVertical: 11, minWidth: 94, alignItems: 'center' },
  dangerText: { color: '#ffffff', fontWeight: '800' },
});
